export {
  DEFAULT_PASSING_SCORE,
  EXAM_RESULT_LABELS,
  EXAM_TYPE_LABELS,
  MAX_THEORY_SCORE,
  calculateExamStats,
  calculateStudentExamHistory,
  canModifyExamResults,
  canRegisterForExam,
  getExamResultLabel,
  getExamTypeLabel,
  getResultByScore,
  isGibddExam,
  isInternalExam,
  isPassingScore,
  isTheoryExam,
  validateExamScore,
  type ExamAttempt,
  type ExamResult,
  type ExamSessionStatus,
  type ExamStats,
  type ExamType,
  type StudentExamHistory,
} from './exam-service'
