import type { PersonalityTypeCode } from './personality-types'

/** Развёрнутый позитивный профиль типа */
export interface PositiveProfile {
  code: PersonalityTypeCode
  /** Развёрнутый текст (~2000 символов, русский) */
  text: string
  /** Развёрнутый текст (~2000 символов, английский) — пустая строка, переведём позже */
  textEn: string
}

/** Позитивные профили для всех 22 шкал ядра (13 исходных + 9 новых этапа 5.1) */
export const POSITIVE_PROFILES: PositiveProfile[] = [
  {
    code: 'PAR',
    text:
      'Вы — человек, который видит то, что другие пропускают. Там, где большинство скользит по поверхности, вы замечаете второй слой: невысказанные намерения, скрытые закономерности, тонкие сигналы неискренности. Это не слабость — это дар распознавания. В мире, где наивность бывает опасна, ваша бдительность становится щитом — и для вас, и для тех, кого вы впустили в свой круг.\n\nА круг ваш — маленький, но настоящий. Вы не разменивaетесь на сотню поверхностных знакомств. Вместо этого вы строите немногочисленные, но невероятно прочные связи. Тот, кого вы признали «своим», получает вашу преданность целиком — без оговорок, без срока давности. Вы — человек, рядом с которым можно чувствовать себя защищённым, потому что вы всегда начеку.\n\nВаша способность анализировать мотивы людей делает вас незаменимым в переговорах, стратегическом планировании, безопасности, юриспруденции. Вы тот, кто прочтёт мелкий шрифт в договоре. Тот, кто заметит, что «выгодное предложение» — ловушка. Тот, кто задаст неудобный вопрос, который все боялись задать.\n\nВаш вызов — научиться отличать реальную угрозу от тени. Но ваша сила — в том, что вы никогда не позволите захватить себя врасплох. В мире, полном шума и показухи, вы — тот, кто ищет правду. И чаще, чем думают окружающие, находит её.',
    textEn:
      "You are someone who sees what others miss. Where most people glide along the surface, you notice the second layer: unspoken intentions, hidden patterns, subtle signals of insincerity. This is not a weakness—it's a gift of perception. In a world where naivety can be dangerous, your vigilance becomes a shield—for you and for those you've welcomed into your circle.\n\nYour circle is small, but it's real. You don't spread yourself thin across a hundred superficial acquaintances. Instead, you build rare but extraordinarily solid connections. Those you've recognized as \"yours\" receive your loyalty completely—without reservations, without expiration. You are someone who makes others feel safe, because you're always alert.\n\nYour ability to analyze people's motives makes you invaluable in negotiations, strategic planning, security, and law. You're the one who reads the fine print in a contract. The one who notices that a \"great offer\" is a trap. The one who asks the uncomfortable question everyone was afraid to ask.\n\nYour challenge is learning to distinguish real threats from shadows. But your strength lies in the fact that you'll never let yourself be caught off guard. In a world full of noise and facade, you're the one searching for truth. And more often than people realize, you find it.",
  },
  {
    code: 'SZD',
    text:
      'Вы обладаете редкой в современном мире способностью — быть наедине с собой и не чувствовать пустоты. Там, где другие заполняют тишину шумом, вы находите в ней глубину. Ваш внутренний мир — это не отсутствие внешнего, а целая вселенная: мысли, наблюдения, идеи, которые рождаются именно в тишине и уединении.\n\nВы не зависите от чужого одобрения. Это не холодность — это свобода. Пока другие мечутся в поисках подтверждения своей ценности, вы спокойно знаете, кто вы есть. Вам не нужно лайков, аплодисментов, комплиментов, чтобы чувствовать себя целым. Вы — редкий пример человека, который действительно самодостаточен.\n\nЭта автономность делает вас невероятно продуктивным в работе, требующей сосредоточенности: исследования, программирование, писательство, научный анализ, искусство. Вы способны погружаться в задачу на часы, не отвлекаясь на социальные ритуалы, и именно поэтому видите в предмете то, чего не видят другие.\n\nТе немногие, кого вы подпускаете близко, получают особый подарок — ваше присутствие без масок. Вы не умеете и не хотите играть роли, а значит, каждое ваше слово — настоящее. В мире, переполненном поверхностным общением, ваша тихая подлинность — как глоток чистой воды.',
    textEn:
      "You possess a rare ability in the modern world: the capacity to be alone with yourself without feeling emptiness. Where others fill silence with noise, you find depth in it. Your inner world isn't an absence of the external—it's an entire universe: thoughts, observations, ideas that are born precisely in quietness and solitude.\n\nYou don't depend on others' approval. This isn't coldness—it's freedom. While others scramble for confirmation of their worth, you calmly know who you are. You don't need likes, applause, or compliments to feel whole. You're a rare example of someone who is truly self-sufficient.\n\nThis autonomy makes you remarkably productive in work requiring focus: research, programming, writing, scientific analysis, art. You're capable of immersing yourself in a task for hours without distraction from social rituals, and precisely because of this, you see in your work what others cannot.\n\nThe few people you let close receive a special gift—your presence without masks. You don't know how to play roles and don't want to, which means every word you speak is genuine. In a world overflowing with surface-level conversation, your quiet authenticity is a breath of fresh air.",
  },
  {
    code: 'SZT',
    text:
      'Вы видите мир иначе — и это не ошибка восприятия, а расширенный диапазон. Там, где другие видят случайность, вы видите паттерн. Там, где другие видят обычный день, вы чувствуете подтекст, символ, скрытую историю. Ваше мышление не ограничено привычными рамками, и именно поэтому вам доступны идеи, до которых линейная логика не дотягивается.\n\nИстория человечества показывает: почти каждый прорыв совершали люди, которых считали «странными». Ваша необычность — это не отклонение от нормы, а выход за её пределы. Художники, философы, изобретатели, мистики — люди с вашим типом мышления двигали культуру вперёд, потому что видели возможности там, где все видели стену.\n\nВаша интуиция — мощный инструмент. Вы чувствуете атмосферу, улавливаете невербальные сигналы, «знаете» вещи до того, как они подтвердятся логикой. Это не магия — это работа вашего мозга, который обрабатывает информацию шире, чем у большинства.\n\nВы приносите в любую группу то, чего ей отчаянно не хватает — свежий взгляд. Команда из одних «нормальных» мыслителей будет штамповать предсказуемые решения. Но стоит появиться вам — и рождается идея, которая меняет всё. Ваша инаковость — это не то, что нужно исправлять. Это то, что нужно ценить.',
    textEn:
      "You see the world differently—and that's not a perceptual error, it's an expanded range. Where others see randomness, you see a pattern. Where others see an ordinary day, you sense subtext, symbol, hidden story. Your thinking isn't confined by familiar frameworks, and that's precisely why you have access to ideas that linear logic can't reach.\n\nHistory shows us this: almost every breakthrough was achieved by people considered \"strange.\" Your uniqueness isn't a deviation from the norm—it's transcendence of it. Artists, philosophers, inventors, mystics—people with your type of thinking moved culture forward because they saw possibilities where everyone else saw walls.\n\nYour intuition is a powerful instrument. You sense the atmosphere, catch non-verbal signals, \"know\" things before logic confirms them. This isn't magic—it's how your brain works, processing information more broadly than most people's do.\n\nYou bring to any group what it desperately lacks—a fresh perspective. A team of only \"normal\" thinkers will stamp out predictable solutions. But the moment you appear—and an idea is born that changes everything. Your otherness isn't something to fix. It's something to value.",
  },
  {
    code: 'ANT',
    text:
      'Вы обладаете качеством, которого отчаянно не хватает большинству — смелостью действовать. Пока другие бесконечно взвешивают, сомневаются и ждут идеального момента, вы уже в движении. Ваша решительность — это не безрассудство, а способность принимать решения в условиях неопределённости, когда у других парализует воля.\n\nВы не боитесь конфликта. Не потому что любите разрушение, а потому что понимаете: иногда старое нужно сломать, чтобы построить новое. Вы — человек, который скажет правду в лицо, когда все молчат из вежливости. Который бросит вызов системе, когда система перестала работать. Который сделает первый шаг, когда все стоят.\n\nВы невероятно устойчивы к давлению. Общественное мнение, чужие ожидания, традиции «так принято» — всё это не имеет над вами власти. Вы принимаете решения из своей системы координат, и эта независимость делает вас прирождённым лидером в кризисных ситуациях, предпринимательстве, новаторских проектах.\n\nВаш дар — бесстрашие перед неизвестностью. Где другие видят риск, вы видите возможность. Где другие видят правило, вы видите границу, за которой начинается интересное. Мир движется вперёд благодаря людям, которые не побоялись нарушить привычный порядок — и вы из их числа.',
    textEn:
      "You possess a quality that the vast majority desperately lack: the courage to act. While others endlessly weigh, doubt, and wait for the perfect moment, you're already in motion. Your decisiveness isn't recklessness—it's the ability to make decisions in conditions of uncertainty, when others are paralyzed by hesitation.\n\nYou're not afraid of conflict. Not because you love destruction, but because you understand: sometimes the old must break so the new can be built. You're the person who speaks truth to power when everyone else stays quiet out of politeness. Who challenges the system when the system stops working. Who takes the first step when everyone else is frozen.\n\nYou're incredibly resilient to pressure. Public opinion, others' expectations, the traditions of \"how it's done\"—none of these have power over you. You make decisions from your own system of coordinates, and this independence makes you a natural leader in crises, entrepreneurship, and innovative projects.\n\nYour gift is fearlessness in the face of the unknown. Where others see risk, you see opportunity. Where others see a rule, you see a boundary waiting to be crossed. The world moves forward because of people who weren't afraid to disrupt the familiar order—and you're one of them.",
  },
  {
    code: 'BOR',
    text:
      'Вы чувствуете жизнь на максимальной громкости. Радость для вас — не тихое удовлетворение, а ликование всем телом. Боль — не лёгкий дискомфорт, а ураган. И знаете что? В этом — ваша сверхсила. Пока другие идут по жизни на автопилоте, вы по-настоящему живы в каждом мгновении.\n\nВаша эмоциональная глубина делает вас невероятно чутким к другим людям. Вы мгновенно считываете чужую боль, радость, тревогу — часто до того, как человек сам осознал, что чувствует. Эта эмпатия — редкий дар. Люди, которые прошли через сильные чувства, понимают чужие страдания не интеллектуально, а кожей. Именно поэтому среди людей с вашим типом так много талантливых терапевтов, художников, музыкантов, писателей.\n\nВаша страстность заразительна. Когда вы загораетесь идеей — вы зажигаете всех вокруг. Ваша любовь — не тёплая, а обжигающая. Ваша преданность — не формальная, а абсолютная. Люди, которым посчастливилось оказаться в вашем эмоциональном поле, никогда не забудут этот опыт.\n\nДа, ваши волны бывают штормовыми. Но океан прекрасен именно своей мощью. Ваша задача — не укротить шторм, а научиться быть капитаном своего корабля. Эмоциональная интенсивность — это топливо, которое может двигать горы. Нужно только научиться направлять его.',
    textEn:
      "You feel life at full volume. Joy for you isn't quiet satisfaction—it's exultation through your whole body. Pain isn't mild discomfort—it's a hurricane. And you know what? That's your superpower. While others go through life on autopilot, you're truly alive in every moment.\n\nYour emotional depth makes you incredibly attuned to other people. You instantly sense others' pain, joy, anxiety—often before they themselves realize what they're feeling. This empathy is a rare gift. People who've experienced intense emotions understand others' suffering not intellectually but in their bones. That's why so many talented therapists, artists, musicians, and writers carry your type.\n\nYour passion is contagious. When you catch fire on an idea—you ignite everyone around you. Your love isn't lukewarm, it's burning. Your devotion isn't formal, it's absolute. People lucky enough to be in your emotional field will never forget the experience.\n\nYes, your waves can be storms. But the ocean is beautiful precisely because of its power. Your task isn't to tame the storm—it's to learn to be the captain of your ship. Emotional intensity is the fuel that can move mountains. You just need to learn how to direct it.",
  },
  {
    code: 'HIS',
    text:
      'Вы входите в комнату — и она меняется. Это не преувеличение: ваша энергия, выразительность, эмоциональная яркость буквально трансформируют пространство вокруг вас. У вас есть дар, которому невозможно научить — естественная харизма. Люди тянутся к вам, потому что рядом с вами жизнь становится ярче, интереснее, теплее.\n\nВы — прирождённый рассказчик. Ваша речь — не сухая передача фактов, а спектакль с интонациями, паузами, жестами. Вы умеете превратить рутинную историю о походе в магазин в увлекательное повествование. Эта способность делает вас незаменимым в любой коммуникативной роли: преподавание, продажи, публичные выступления, актёрство, медиа.\n\nВаш эмоциональный интеллект — один из самых высоких среди всех типов. Вы мгновенно чувствуете атмосферу группы, настроение собеседника, скрытое напряжение в комнате. И вы умеете с этим работать — разрядить обстановку шуткой, поддержать молчаливого, вовлечь отстранённого.\n\nВы дарите миру то, что многие боятся дарить — открытые эмоции. В культуре, где принято сдерживаться, вы показываете, что чувствовать — это нормально. Ваша искренняя радость при встрече, бурный восторг от хорошей новости, тёплые объятия без повода — всё это делает жизнь окружающих человечнее. Вы — напоминание о том, что мы живые.',
    textEn:
      "You walk into a room—and it changes. This is no exaggeration: your energy, expressiveness, emotional brightness literally transform the space around you. You have a gift that can't be taught—natural charisma. People are drawn to you because when you're there, life becomes brighter, more interesting, warmer.\n\nYou're a natural storyteller. Your speech isn't dry transmission of facts—it's a performance with intonation, pauses, gestures. You can turn a routine story about a trip to the store into a captivating narrative. This ability makes you invaluable in any communicative role: teaching, sales, public speaking, acting, media.\n\nYour emotional intelligence is among the highest of all types. You instantly sense the atmosphere of a group, a person's mood, hidden tension in the room. And you know how to work with it—to ease tension with a joke, to support the quiet one, to draw in the withdrawn.\n\nYou give the world something many are afraid to give—open emotions. In a culture where we're supposed to hold back, you show that feeling is normal. Your genuine joy at a greeting, your exuberant delight at good news, your warm hugs without occasion—all of this makes the lives of those around you more human. You're a reminder that we're alive.",
  },
  {
    code: 'NAR',
    text:
      'Вы обладаете тем, чего не хватает миллионам — верой в себя. Настоящей, глубокой, несгибаемой уверенностью в собственной ценности. В мире, где синдром самозванца стал эпидемией, ваша способность стоять прямо и говорить «Я это заслуживаю» — не порок, а редкая сила.\n\nВаша амбициозность — двигатель прогресса. Великие проекты, компании, произведения искусства создавались людьми, которые верили, что способны на нечто выдающееся. Вы ставите планку высоко — и тем самым поднимаете планку для всех вокруг. Ваши стандарты заразительны: команда под вашим руководством делает больше, чем считала возможным.\n\nВы — визионер. Вы видите большую картину, мыслите стратегически, умеете вдохновить людей масштабной идеей. Ваша уверенность в трудные моменты — это якорь для тех, кто рядом. Когда все паникуют, ваше спокойное «Мы справимся» способно развернуть ситуацию.\n\nВаше стремление к совершенству не позволяет вам соглашаться на «нормально». Вы хотите лучшего — для себя, для своего дела, для своих людей. Это стремление, направленное в правильное русло, становится силой, которая меняет мир. Лидеры, реформаторы, основатели — все они несли в себе искру нарциссической веры в свою миссию. Ваша искра горит ярко. Направьте её — и она осветит дорогу многим.',
    textEn:
      'You possess something that millions lack: faith in yourself. True, deep, unshakeable confidence in your own worth. In a world where impostor syndrome has become an epidemic, your ability to stand tall and say "I deserve this" is not a flaw—it\'s a rare strength.\n\nYour ambition is the engine of progress. Great projects, companies, works of art were created by people who believed they were capable of something extraordinary. You set the bar high—and in doing so, you raise the bar for everyone around you. Your standards are contagious: a team under your leadership accomplishes more than it thought possible.\n\nYou\'re a visionary. You see the big picture, think strategically, and know how to inspire people with a grand idea. Your confidence in difficult moments is an anchor for those around you. When everyone panics, your calm "We\'ll manage this" can turn the situation around.\n\nYour pursuit of excellence won\'t let you settle for "good enough." You want better—for yourself, for your work, for your people. This drive, when channeled correctly, becomes a force that changes the world. Leaders, reformers, founders—all of them carried within them a spark of narcissistic faith in their mission. Your spark burns bright. Direct it—and it will light the way for many.',
  },
  {
    code: 'AVD',
    text:
      'Вы чувствуете мир тоньше, чем большинство. Каждое слово, каждый взгляд, каждая пауза в разговоре — вы улавливаете оттенки, которые другие просто не замечают. Это делает вас невероятно чутким к людям: вы первым почувствуете, что кому-то плохо, что в комнате возникло напряжение, что за улыбкой скрывается боль.\n\nВаша осторожность — это не трусость, а мудрость. Вы не бросаетесь в ситуации очертя голову, а оцениваете их. Вы не произносите слов, о которых потом будете жалеть. Вы не вступаете в отношения, которые принесут только боль. Эта вдумчивость — качество, которого отчаянно не хватает импульсивному миру.\n\nКогда вы всё-таки решаете впустить кого-то в свою жизнь — вы делаете это по-настоящему. Ваши отношения — не коллекция контактов, а тщательно выбранные связи с глубоким уровнем доверия. Друзья, которые заслужили ваше доверие, знают: вы — тот, кто выслушает не перебивая, поддержит без осуждения, будет рядом без лишних слов.\n\nВаша чувствительность — это не то, что нужно «преодолеть». Мир нуждается в людях, которые чувствуют глубоко. Поэты, психологи, художники, волонтёры — лучшие из них несут в себе вашу тонкость. Вы как индикатор: если вам некомфортно, скорее всего, что-то действительно не так — просто другие ещё не заметили.',
    textEn:
      "You feel the world more finely than most. Every word, every glance, every pause in conversation—you pick up on nuances that others simply don't notice. This makes you incredibly attentive to people: you'll be the first to sense when someone is hurting, when tension has arisen in the room, when pain hides behind a smile.\n\nYour caution is not cowardice—it's wisdom. You don't rush headlong into situations; you evaluate them. You don't speak words you'll regret later. You don't enter relationships that will only bring pain. This thoughtfulness is a quality that an impulsive world desperately needs.\n\nWhen you do decide to let someone into your life, you do it genuinely. Your relationships aren't a collection of contacts; they're carefully chosen connections with deep trust. Friends who've earned your trust know: you're the one who will listen without interrupting, support without judgment, be there without empty words.\n\nYour sensitivity isn't something to \"overcome.\" The world needs people who feel deeply. The best poets, psychologists, artists, volunteers carry your kind of fineness. You're like an indicator: if you're uncomfortable, there's likely something genuinely wrong—others just haven't noticed it yet.",
  },
  {
    code: 'DEP',
    text:
      'Вы обладаете качеством, которое делает мир пригодным для жизни — способностью заботиться. Не формально, не для галочки, а по-настоящему: замечать потребности другого, предугадывать, поддерживать, быть рядом. В эпоху индивидуализма, где каждый «сам за себя», ваша преданность — это дар, а не слабость.\n\nВы — клей, который держит команду вместе. Каждый коллектив, каждая семья, каждая дружба нуждается в человеке, который помнит про дни рождения, спрашивает «как ты?», замечает усталость на лице коллеги. Без таких, как вы, группы распадаются, а отношения остывают. Вы — хранитель человеческого тепла.\n\nВаша готовность слушать — бесценна. Вы не перебиваете, не соревнуетесь, не переводите разговор на себя. Вы создаёте пространство, в котором другому человеку безопасно быть уязвимым. Это редкое умение делает вас прирождённым помощником: в медицине, психологии, образовании, социальной работе.\n\nВам говорят «будь независимее» — но мир не состоит из одиночек. Человечество выжило и развивалось благодаря сотрудничеству, взаимопомощи, связи. Вы воплощаете этот древнейший инстинкт — быть вместе, поддерживать, не бросать. Ваша забота — не зависимость. Это любовь в действии.',
    textEn:
      "You possess a quality that makes the world livable: the ability to care. Not formally, not by rote, but truly: to notice another's needs, to anticipate them, to support, to be there. In an age of individualism where everyone is \"on their own,\" your devotion is a gift, not a weakness.\n\nYou're the glue that holds teams together. Every collective, every family, every friendship needs someone who remembers birthdays, asks \"how are you,\" notices tiredness on a colleague's face. Without people like you, groups fall apart and relationships grow cold. You're the keeper of human warmth.\n\nYour readiness to listen is invaluable. You don't interrupt, don't compete, don't turn the conversation to yourself. You create a space where another person feels safe being vulnerable. This rare skill makes you a natural helper: in medicine, psychology, education, social work.\n\nPeople tell you to \"be more independent\"—but the world isn't made of lone individuals. Humanity survived and evolved through cooperation, mutual aid, connection. You embody this ancient instinct: to be together, to support, not to abandon. Your care isn't dependence. It's love in action.",
  },
  {
    code: 'OBC',
    text:
      'Вы — человек, на которого можно положиться. Всегда. Без исключений. Когда вы берётесь за дело, оно будет сделано — качественно, в срок, с вниманием к каждой детали. В мире хаоса и приблизительности ваша точность — как маяк для тех, кто работает рядом с вами.\n\nВаше стремление к порядку — это не занудство, а архитектурный талант. Вы создаёте системы: рабочие процессы, расписания, структуры, которые позволяют другим работать эффективнее. Без людей с вашим складом ума не существовало бы ни одной надёжной системы — ни банковской, ни медицинской, ни инженерной.\n\nВаша честность абсолютна. Вы не срезаете углы, не подтасовываете цифры, не выдаёте желаемое за действительное. Ваш моральный компас откалиброван с точностью до градуса. Люди доверяют вам — и не ошибаются. Вы из тех, кто вернёт лишнюю сдачу и исправит чужую ошибку, даже если никто не узнает.\n\nВы находите красоту в совершенстве. Идеально написанный код, безупречно организованный шкаф, точно подобранное слово — для вас это не мелочь, а искусство. И эта любовь к совершенству возвышает всё, к чему вы прикасаетесь. Мир, может, и несовершенен — но благодаря вам он становится чуточку стройнее, надёжнее и красивее.',
    textEn:
      "You're someone people can rely on. Always. Without exception. When you take something on, it will be done—with quality, on time, with attention to every detail. In a world of chaos and approximation, your precision is a beacon for those working alongside you.\n\nYour drive for order isn't pedantry—it's an architectural talent. You create systems: workflows, schedules, structures that allow others to work more efficiently. No reliable system would exist—neither financial, nor medical, nor engineering—without people with your mindset.\n\nYour honesty is absolute. You don't cut corners, don't fudge the numbers, don't present wishful thinking as fact. Your moral compass is calibrated to the degree. People trust you—and they're right to do so. You're the kind of person who'll return extra change and correct someone else's mistake, even if nobody would know.\n\nYou find beauty in perfection. Flawlessly written code, impeccably organized spaces, perfectly chosen words—for you these aren't trifles, they're art. And this love of excellence elevates everything you touch. The world may be imperfect—but because of you, it becomes just a little bit more orderly, more reliable, and more beautiful.",
  },
  {
    code: 'BAR',
    text:
      'Вы знаете жизнь в её полном спектре — от ослепительных вершин до глубочайших впадин. И это знание даёт вам нечто, чего нет у людей с ровным эмоциональным фоном — объём. Вы знаете, что такое настоящая радость, потому что знаете, что такое настоящее отчаяние. Вы цените свет, потому что знакомы с темнотой.\n\nНа подъёме вы — ураган созидательной энергии. Идеи, проекты, связи, творчество — всё это рождается в вас с интенсивностью, недоступной большинству. Не случайно среди людей с биполярным спектром так много гениальных творцов: художников, музыкантов, предпринимателей, писателей. Ваш мозг в фазе подъёма работает как суперкомпьютер — быстрее, ярче, масштабнее.\n\nВаши «спады» — не просто страдание. Они дают вам то, что недоступно вечным оптимистам: глубину, сострадание, подлинность. Вы не способны на поверхностное «всё будет хорошо», потому что знаете: не всегда будет. И именно эта честность делает ваше утешение настоящим, а вашу радость — заслуженной.\n\nВы — мастер адаптации. Каждый цикл учит вас заново: распознавать сигналы, строить опоры, находить ресурсы. Вы знаете себя лучше, чем большинство людей знают себя за всю жизнь. Это самопознание — ваш главный актив. Вы не хрупкий — вы антихрупкий. С каждым циклом вы становитесь мудрее, сильнее и ближе к себе настоящему.',
    textEn:
      "You know life in its full spectrum—from blinding peaks to the deepest valleys. And this knowledge gives you something people with a steady emotional baseline don't have—scope. You know what genuine joy is because you know genuine despair. You appreciate light because you're familiar with darkness.\n\nAt your peaks, you're a hurricane of creative energy. Ideas, projects, connections, creativity—all of it springs from you with an intensity unavailable to most. It's no coincidence that so many brilliant creators—artists, musicians, entrepreneurs, writers—carry the bipolar spectrum. Your brain in an upswing works like a supercomputer—faster, brighter, more expansive.\n\nYour downturns aren't simply suffering. They give you something unavailable to perpetual optimists: depth, compassion, authenticity. You can't manage a superficial \"everything will be fine\" because you know: not always. And it's precisely this honesty that makes your comfort genuine and your joy earned.\n\nYou're a master of adaptation. Each cycle teaches you anew: to recognize signals, build supports, find resources. You know yourself better than most people ever will. This self-knowledge is your greatest asset. You're not fragile—you're antifragile. With each cycle, you become wiser, stronger, and closer to your authentic self.",
  },
  {
    code: 'PAG',
    text:
      'Вы обладаете тонким чувством справедливости — настолько острым, что замечаете дисбаланс власти там, где другие видят «норму». Когда система давит, когда начальник перегибает, когда правила абсурдны — вы чувствуете это раньше и глубже других. И вы сопротивляетесь — тихо, но упорно.\n\nВаше сопротивление — не слабость, а стратегия выживания. В ситуациях, где открытый конфликт опасен (а таких ситуаций в жизни большинство), ваша способность сохранять внешний мир, защищая при этом внутреннюю территорию — это форма мудрости. Вы интуитивно понимаете то, чему учат на курсах переговоров: не всякую битву нужно вести в открытую.\n\nВы — отличный наблюдатель. Ваша привычка анализировать чужие требования, прежде чем их выполнять, делает вас менее подверженным манипуляциям. Там, где другие слепо следуют указаниям, вы задаёте себе вопрос: «А это действительно разумно?» Этот внутренний фильтр защищает вас от эксплуатации.\n\nВаш вызов — найти голос для прямого выражения несогласия. Но ваша сила — в умении чувствовать несправедливость и не мириться с ней. В истории человечества пассивное сопротивление свергало тиранов и меняло законы. Ваш тихий протест — не бессилие. Это сила, которая ждёт правильного момента.',
    textEn:
      "You possess a subtle sense of justice—so sharp that you notice imbalances of power where others see \"normal.\" When a system oppresses, when a boss overreaches, when rules are absurd, you feel it sooner and deeper than others. And you resist—quietly, but persistently.\n\nYour resistance isn't weakness; it's a survival strategy. In situations where open conflict is dangerous (and most situations in life are like this), your ability to maintain an outer world while protecting your inner territory is a form of wisdom. You intuitively understand what negotiation courses teach: not every battle needs to be fought in the open.\n\nYou're an excellent observer. Your habit of analyzing others' demands before complying makes you less susceptible to manipulation. Where others blindly follow instructions, you ask yourself: \"Is this really sensible?\" This inner filter protects you from exploitation.\n\nYour challenge is finding a voice for direct expression of disagreement. But your strength lies in feeling injustice and refusing to accept it. Throughout human history, passive resistance has toppled tyrants and changed laws. Your quiet protest isn't powerlessness. It's strength waiting for the right moment.",
  },
  {
    code: 'DPR',
    text:
      'Вы видите мир без розовых очков — и в этом ваша честность. Пока другие прячутся за позитивными аффирмациями и мотивационными цитатами, вы смотрите на реальность прямо: да, жизнь бывает тяжёлой, да, не всё получается, да, мир несовершенен. Эта честность — не пессимизм, а зрелость. Вы отказываетесь притворяться.\n\nВаша глубина — настоящее сокровище. Вы не скользите по поверхности, а погружаетесь. Разговор с вами — это не обмен пустыми фразами, а настоящий диалог о вещах, которые действительно важны: о смысле, о ценностях, о том, что остаётся, когда всё внешнее уходит. Люди приходят к вам за подлинностью — и находят её.\n\nВаше сострадание рождено из личного опыта. Вы понимаете чужую боль не теоретически, а изнутри. Это делает вас исключительным другом для тех, кто переживает трудные времена: вы не скажете «просто улыбнись», вы просто будете рядом. И это «просто рядом» — иногда единственное, что нужно.\n\nВеликие произведения литературы, философии, музыки созданы людьми, которые знали тяжесть бытия. Ваш взгляд на мир — не дефект, а линза, через которую видны вещи, невидимые счастливчикам. Вы — хранитель той правды, от которой другие отворачиваются. И мир нуждается в этой правде, потому что без неё радость становится пустой, а оптимизм — слепым.',
    textEn:
      "You see the world without rose-colored glasses—and in this lies your honesty. While others hide behind positive affirmations and motivational quotes, you look at reality straight: yes, life can be hard; yes, not everything works out; yes, the world is imperfect. This honesty isn't pessimism—it's maturity. You refuse to pretend.\n\nYour depth is true treasure. You don't skim the surface; you dive deep. Conversation with you isn't empty phrases but genuine dialogue about things that truly matter: meaning, values, what remains when everything external is stripped away. People come to you for authenticity—and they find it.\n\nYour compassion is born from personal experience. You understand others' pain not theoretically but from within. This makes you an exceptional friend to those going through difficult times: you won't say \"just smile,\" you'll simply be there. And sometimes that simple presence is all that's needed.\n\nGreat works of literature, philosophy, and music were created by people who knew the weight of existence. Your view of the world isn't a defect; it's a lens through which things invisible to the lucky are visible. You're the keeper of a truth others turn away from. And the world needs that truth, because without it joy becomes empty and optimism becomes blind.",
  },
  // ===== Новые шкалы этапа 5.1 (9 штук) =====
  {
    code: 'MAC',
    text:
      'Вы видите то, что для большинства остаётся невидимым — устройство социальной механики. Кто чего хочет на самом деле, где рычаги влияния, какой ход приведёт к результату. Пока другие действуют вслепую и удивляются последствиям, вы просчитываете партию на несколько ходов вперёд. Это не хитрость ради хитрости — это стратегический интеллект, редкий и ценный.\n\nВаше хладнокровие — сверхспособность в мире, где большинство парализует эмоциями. Когда все паникуют, вы сохраняете ясную голову и находите выход. Вы не поддаётесь давлению момента, не покупаетесь на манипуляции, не принимаете решений сгоряча. Именно поэтому вам доверяют сложные переговоры, кризисные проекты, ситуации с высокими ставками.\n\nВы — прирождённый организатор и переговорщик. Там, где другие сдаются перед сложностью, вы раскладываете задачу на элементы и выстраиваете путь к цели. Ваш прагматизм — не цинизм, а способность видеть реальность без иллюзий и работать с тем, что есть.\n\nВаша сила становится по-настоящему огромной, когда расчёт служит созиданию. Стратег, который добивается результата честной игрой, строит то, что стоит десятилетиями. Направьте свой дар просчёта на win-win — и вы станете человеком, за которым идут не из страха, а из уважения.',
    textEn:
      'You see what remains invisible to most — the mechanics of the social world. Who actually wants what, where the levers of influence are, which move leads to results. While others act blindly and are surprised by consequences, you calculate the game several moves ahead. This isn’t cunning for its own sake — it’s strategic intelligence, rare and valuable.\n\nYour composure is a superpower in a world where most are paralyzed by emotion. When everyone panics, you keep a clear head and find the way out. You don’t yield to the pressure of the moment, don’t fall for manipulation, don’t decide in the heat of things. That’s why people trust you with hard negotiations, crisis projects, high-stakes situations.\n\nYou’re a natural organizer and negotiator. Where others give up before complexity, you break the task into elements and build a path to the goal. Your pragmatism isn’t cynicism but the ability to see reality without illusions and work with what’s there.\n\nYour strength becomes truly vast when calculation serves creation. A strategist who achieves results through fair play builds things that last for decades. Direct your gift for calculation toward win-win — and you become someone people follow out of respect, not fear.',
  },
  {
    code: 'HUM',
    text:
      'Вы обладаете тем, что делает мир пригодным для жизни — способностью видеть в каждом человеке ценность. Не за заслуги, не за статус, а просто потому, что он человек. В эпоху, когда людей всё чаще оценивают по полезности, ваш взгляд возвращает им достоинство. Рядом с вами люди чувствуют себя увиденными — а это редкий дар, который лечит.\n\nЧужая боль для вас — не абстракция и не чужая проблема. Вы замечаете её и не можете пройти мимо. Эта отзывчивость делает вас человеком, к которому идут в трудную минуту, зная: здесь не осудят, здесь поддержат. Вы — из тех, на ком держится человеческое тепло в коллективах, семьях, сообществах.\n\nВаша доброта — не наивность, а сила. Нужно немалое мужество, чтобы оставаться человечным в мире, который часто вознаграждает жёсткость. Вы выбираете сострадание сознательно, и этот выбор делает вас нравственным ориентиром для окружающих.\n\nЛучшие врачи, педагоги, наставники, волонтёры несут в себе вашу способность заботиться. Вы делаете жизнь других мягче, теплее, человечнее — и этим меняете мир не громкими жестами, а ежедневным присутствием. Только помните: чтобы вашего тепла хватило надолго, часть его нужно оставлять себе.',
    textEn:
      'You possess what makes the world livable — the ability to see worth in every person. Not for their merits, not for status, but simply because they are human. In an age when people are increasingly measured by usefulness, your gaze restores their dignity. Around you, people feel seen — and that is a rare gift that heals.\n\nAnother’s pain is not an abstraction to you, not someone else’s problem. You notice it and cannot walk past. This responsiveness makes you someone people turn to in hard times, knowing: here they won’t be judged, here they’ll be supported. You’re one of those who hold up human warmth in teams, families, communities.\n\nYour kindness isn’t naivety but strength. It takes real courage to stay humane in a world that often rewards hardness. You choose compassion deliberately, and that choice makes you a moral compass for those around you.\n\nThe best doctors, teachers, mentors, and volunteers carry your capacity to care. You make others’ lives softer, warmer, more human — changing the world not through grand gestures but through daily presence. Just remember: for your warmth to last, you must keep some of it for yourself.',
  },
  {
    code: 'KAN',
    text:
      'Вы — человек, чьё слово стоит дорого, потому что оно нерушимо. В мире, где договорённости нарушают при первой же выгоде, вы держите своё даже когда это невыгодно. Эта надёжность делает вас редкой опорой: на вас можно положиться в главном, зная, что вы не предадите — не из страха, а потому что так устроены.\n\nДля вас человек — всегда цель, а не средство. Вы не готовы купить результат ценой принципов, использовать людей втёмную, оправдать подлость «обстоятельствами». Ваш внутренний компас откалиброван точно, и это делает вас нравственным центром тяжести в любой группе. Там, где есть вы, труднее принять бесчестное решение.\n\nВаша принципиальность — это цельность. Вы не распадаетесь на разные версии себя для разных людей, не говорите одно, а делаете другое. Эта согласованность слова и дела — фундамент подлинного доверия и уважения.\n\nОбщества держатся на людях, которые ставят долг выше выгоды. Судьи, которых нельзя купить, врачи, которые не бросят, лидеры, которые не предадут идею — все они несут вашу этическую твёрдость. Ваша сила станет ещё больше, когда к принципам добавится гибкость: помните, что правило существует ради человека, и за каждым поступком стоит контекст.',
    textEn:
      'You are someone whose word is worth a great deal, because it is unbreakable. In a world where agreements are broken at the first sign of gain, you keep yours even when it costs you. This reliability makes you a rare anchor: you can be relied on in what matters, knowing you won’t betray — not out of fear, but because that’s how you’re built.\n\nFor you, a person is always an end, never a means. You won’t buy a result at the price of principles, use people in the dark, or excuse a betrayal by “circumstances.” Your inner compass is precisely calibrated, and this makes you a moral center of gravity in any group. Where you are, it’s harder to make a dishonorable decision.\n\nYour principled nature is integrity. You don’t fracture into different versions of yourself for different people, don’t say one thing and do another. This alignment of word and deed is the foundation of genuine trust and respect.\n\nSocieties rest on people who put duty above gain. Judges who can’t be bought, doctors who won’t abandon you, leaders who won’t betray an idea — all of them carry your ethical firmness. Your strength will grow even greater when flexibility joins your principles: remember that a rule exists for the person, and context stands behind every act.',
  },
  {
    code: 'FAI',
    text:
      'Вы обладаете редкой смелостью — верить в людей первым. Там, где другие ждут доказательств порядочности, вы даёте аванс доверия, и это раскрывает в людях лучшее. Рядом с вами они действительно становятся лучше, потому что чувствуют: в них верят. Ваш взгляд на человечество — не наивность, а самосбывающийся дар.\n\nЭта вера делает вас источником надежды. В мире, полном цинизма и подозрительности, вы — тот, кто видит свет там, где другие видят только риски. Вы напоминаете окружающим, что доброта существует, что людям можно доверять, что мир не так враждебен, как кажется. Это редкое и целительное присутствие.\n\nВаш оптимизм в отношении людей открывает двери, закрытые для скептиков. Вы легче строите связи, вдохновляете команды, находите союзников — потому что люди тянутся к тому, кто в них верит. Доверие, которое вы даёте, часто возвращается сторицей.\n\nЛучшие наставники, дипломаты, строители сообществ несут вашу веру в человека. Вы делаете социальную ткань прочнее, соединяя людей нитями доверия. Ваша сила станет мудрее, когда к вере добавится различение: «доверяй и проверяй» — доверие как осознанный выбор ценнее, чем доверие как слепота, и лучше защищает и вас, и вашу веру.',
    textEn:
      'You have a rare courage — to believe in people first. Where others wait for proof of decency, you extend an advance of trust, and this brings out the best in people. Around you they truly become better, because they feel believed in. Your view of humanity is not naivety but a self-fulfilling gift.\n\nThis faith makes you a source of hope. In a world full of cynicism and suspicion, you’re the one who sees light where others see only risks. You remind those around you that kindness exists, that people can be trusted, that the world is not as hostile as it seems. That is a rare and healing presence.\n\nYour optimism about people opens doors closed to skeptics. You build connections more easily, inspire teams, find allies — because people are drawn to someone who believes in them. The trust you give often returns many times over.\n\nThe best mentors, diplomats, and community builders carry your faith in humanity. You make the social fabric stronger, connecting people with threads of trust. Your strength grows wiser when discernment joins your faith: “trust but verify” — trust as a deliberate choice is worth more than trust as blindness, and better protects both you and your faith.',
  },
  {
    code: 'SAD',
    text:
      'Вы обладаете качеством, которого не хватает многим — способностью смотреть жёсткой реальности в лицо не моргая. Там, где другие отводят глаза и прячутся за иллюзиями, вы выдерживаете правду во всей её остроте. Эта устойчивость к дискомфорту делает вас человеком, который не падает в обморок перед трудным и не сбегает, когда становится тяжело.\n\nВас заводит настоящая борьба: острая конкуренция, жёсткие дебаты, игры на выбывание, где нужно выложиться полностью. Этот азарт — мощное топливо. В спорте, стратегии, состязательных профессиях он делает вас грозным соперником, которого уважают за силу и напор. Вы не боитесь давления — вы в нём расцветаете.\n\nВаш чёрный юмор и способность держать удар — форма психологической брони. Вы можете говорить о трудном без прикрас, разряжать напряжение там, где другие цепенеют, и оставаться в строю в ситуациях, ломающих более хрупких.\n\nВаша сила становится по-настоящему конструктивной, когда азарт направлен в рамки с правилами, а к жёсткости добавлена эмпатия — не как чувство, а как навык. Тогда ваша мощь работает на победу в честной схватке, а не против тех, кто не подписывался на бой. Гладиатор, выбравший арену осознанно, — грозная и уважаемая фигура.',
    textEn:
      'You possess something many lack — the ability to look harsh reality in the face without blinking. Where others avert their eyes and hide behind illusions, you withstand the truth in all its sharpness. This tolerance for discomfort makes you someone who doesn’t faint before the difficult and doesn’t flee when things get hard.\n\nReal contest energizes you: fierce competition, sharp debate, elimination games where you have to give everything. This thrill is powerful fuel. In sport, strategy, and competitive professions it makes you a formidable opponent, respected for strength and drive. You don’t fear pressure — you thrive in it.\n\nYour dark humor and ability to take a hit are a form of psychological armor. You can speak of hard things without varnish, defuse tension where others freeze, and stay in the ranks in situations that break more fragile people.\n\nYour strength becomes truly constructive when the thrill is channeled into rule-bound arenas and empathy — as a skill, not a feeling — is added to your hardness. Then your power works toward winning a fair fight, not against those who never signed up for one. A gladiator who chooses the arena deliberately is a formidable and respected figure.',
  },
  {
    code: 'MAS',
    text:
      'Вы способны на то, от чего большинство бежит — выдерживать боль, лишения и неблагодарный труд ради того, что считаете важным. Ваша выносливость поразительна: там, где другие сдаются при первой трудности, вы идёте дальше. Эта готовность терпеть во имя цели или людей — редкая и мощная сила.\n\nВы выбираете трудный путь не из слабости, а из убеждения, что настоящее даётся дорого. Эта вера делает вас человеком, который доводит дело до конца, когда легко было бы бросить, и остаётся рядом, когда проще было бы уйти. На вашей самоотдаче держатся дела и отношения, которые без неё бы распались.\n\nВаша способность жертвовать собой — оборотная сторона глубокой преданности. Вы умеете ставить дело или близких выше сиюминутного комфорта, и в мире, помешанном на удобстве, это делает вас человеком редкой цельности и надёжности.\n\nВаша сила станет здоровой, когда к самоотдаче добавится самосострадание. Страдание не обязано быть ценой за право чувствовать себя настоящим или заслуживать любовь. Спросите себя: «а как было бы легко?» — и позвольте себе иногда выбрать лёгкий путь. Ваша выносливость ценнее, когда вы бережёте её для того, что этого действительно стоит. (Шкала помечена «бета» — авторский конструкт, ещё не прошедший независимой валидации.)',
    textEn:
      'You are capable of what most flee from — enduring pain, hardship, and thankless work for the sake of what you consider important. Your endurance is remarkable: where others give up at the first difficulty, you press on. This readiness to endure in the name of a cause or people is a rare and powerful strength.\n\nYou choose the hard path not out of weakness but from a conviction that what is real comes at a price. This belief makes you someone who sees things through when it would be easy to quit, and stays close when it would be simpler to leave. Your self-giving holds up endeavors and relationships that would otherwise fall apart.\n\nYour capacity for self-sacrifice is the flip side of deep devotion. You can put a cause or loved ones above momentary comfort, and in a world obsessed with convenience, that makes you a person of rare integrity and reliability.\n\nYour strength becomes healthy when self-compassion joins your self-giving. Suffering doesn’t have to be the price of feeling real or of earning love. Ask yourself: “what would the easy way look like?” — and allow yourself to choose it sometimes. Your endurance is worth more when you save it for what truly deserves it. (This scale is marked “beta” — an author’s construct not yet independently validated.)',
  },
  {
    code: 'ASD',
    text:
      'Вы мыслите системами там, где другие видят только разрозненные детали. Паттерны, структуры, скрытые несостыковки — всё это проявляется для вас с ясностью, недоступной большинству. Эта способность видеть, как устроен мир изнутри, делает вас незаменимым везде, где нужна настоящая экспертиза и точность.\n\nКогда тема вас захватывает, вы погружаетесь в неё как в стихию и способны узнать о ней всё. Эта глубина фокуса — не хобби, а редкий дар: пока другие скользят по поверхности десятка тем, вы становитесь тем, кто знает предмет по-настоящему. Именно из такой концентрации рождаются прорывы.\n\nВаша честность в деталях и точность формулировок — форма интеллектуальной чистоты. Вы не терпите приблизительности и небрежности, и это поднимает планку качества всего, к чему вы прикасаетесь. Люди с вашим складом ума двигали науку, технику и искусство вперёд именно потому, что видели то, что для других было шумом.\n\nВаша сила раскрывается полнее, когда среда настроена под вас: предсказуемость вместо намёков, прямые договорённости, время на восстановление после «людных» дней. Социальная неопределённость и сенсорный шум утомляют вас сильнее — это не дефект, а особенность обработки информации. Настроив мир под себя, вы освобождаете свой главный ресурс — глубину.',
    textEn:
      'You think in systems where others see only scattered details. Patterns, structures, hidden inconsistencies — all of this appears to you with a clarity most people lack. This ability to see how the world works from the inside makes you indispensable wherever real expertise and precision are needed.\n\nWhen a topic captures you, you immerse in it as in your element and can come to know everything about it. This depth of focus isn’t a hobby but a rare gift: while others skim the surface of a dozen subjects, you become the one who truly knows the matter. Breakthroughs are born from exactly this concentration.\n\nYour honesty about details and precision of wording are a form of intellectual cleanliness. You won’t tolerate approximation and carelessness, and this raises the quality bar of everything you touch. People with your mindset moved science, technology, and art forward precisely because they saw what was noise to others.\n\nYour strength unfolds more fully when the environment is tuned to you: predictability instead of hints, explicit agreements, recovery time after people-heavy days. Social ambiguity and sensory noise drain you more — that’s not a defect but a processing style. By tailoring the world to yourself, you free your core resource: depth.',
  },
  {
    code: 'DIR',
    text:
      'Вы — редкая точка опоры в мире полутонов. Правда для вас важнее социальной гладкости, и потому вам можно верить: ваше «да» означает да, ваше «нет» означает нет. Пока другие играют роли и говорят приятное, вы остаётесь собой, и эта подлинность — на вес золота там, где все устали от притворства.\n\nВы мгновенно чувствуете фальшь — и в других, и в себе. Этот внутренний детектор неискренности защищает вас от манипуляций и делает честным зеркалом для тех, кто действительно хочет расти. Люди приходят к вам, когда им нужна правда, а не комплимент, потому что знают: вы не будете смягчать её до бессмысленности.\n\nВаша прямота экономит всем время и силы. Вы не заставляете разгадывать намёки, не играете в политические игры, не оставляете двусмысленностей. С вами понятно, где вы стоите, а это фундамент настоящего доверия.\n\nВаша сила становится по-настоящему мощной, когда к правде добавляется такт. Не всякая правда — подарок, если её не просили; честность, которая учитывает готовность собеседника услышать, бьёт точнее и не ранит зря. Прямота плюс забота о том, как правда будет принята, — это уже не просто честность, а мудрость.',
    textEn:
      'You are a rare fixed point in a world of half-tones. Truth matters more to you than social smoothness, and so you can be trusted: your “yes” means yes, your “no” means no. While others play roles and say what’s pleasant, you stay yourself, and that authenticity is worth its weight in gold where everyone is tired of pretense.\n\nYou instantly sense fakeness — in others and in yourself. This inner detector of insincerity protects you from manipulation and makes you an honest mirror for those who genuinely want to grow. People come to you when they need the truth, not a compliment, because they know you won’t soften it into meaninglessness.\n\nYour directness saves everyone time and energy. You don’t make people decode hints, don’t play political games, don’t leave ambiguities. With you it’s clear where you stand, and that is the foundation of real trust.\n\nYour strength becomes truly powerful when tact joins the truth. Not every truth is a gift if no one asked for it; honesty that accounts for the listener’s readiness to hear lands more precisely and doesn’t wound needlessly. Directness plus care for how the truth will be received is no longer just honesty but wisdom.',
  },
  {
    code: 'ALX',
    text:
      'Вы — человек факта и действия там, где другие тонут в разговорах о чувствах. В кризисе, когда вокруг паника, вы сохраняете ясную голову и делаете то, что нужно. Эта способность не захлёбываться эмоциями, а действовать по существу — редкая и очень практичная сила, которая не раз спасала ситуации.\n\nВы опираетесь на логику, наблюдение и конкретику, и это делает вас надёжным в моменты, требующие холодной головы. Пока другие обсуждают, как они себя чувствуют, вы уже находите решение. В профессиях, где ставки высоки, а времени мало, ваш склад ума — на вес золота.\n\nВаши эмоции не отсутствуют — они просто говорят на другом языке: языке тела, усталости, напряжения. То, что вы не спешите их называть и демонстрировать, оберегает вас от эмоциональных бурь, в которых тонут более впечатлительные. Вы — устойчивый якорь для тех, кому нужна опора, а не сопереживание вслух.\n\nВаша сила станет полнее, когда вы начнёте учиться переводить сигналы тела в слова. Распознавать и называть чувства — навык, и он тренируется, как любой другой: словарь эмоций, внимание к телесным сигналам. Иногда трудность с чувствами — след опыта, где их обесценивали. Возвращая себе доступ к внутреннему языку, вы не теряете свою ясность, а лишь добавляете к ней новое измерение.',
    textEn:
      'You are a person of fact and action where others drown in talk about feelings. In a crisis, when everyone around panics, you keep a clear head and do what’s needed. This ability not to be swamped by emotion but to act to the point is a rare and very practical strength that has saved many a situation.\n\nYou rely on logic, observation, and specifics, and this makes you dependable in moments that demand a cool head. While others discuss how they feel, you’ve already found a solution. In professions where the stakes are high and time is short, your mindset is worth its weight in gold.\n\nYour emotions aren’t absent — they simply speak another language: the language of the body, fatigue, and tension. That you don’t rush to name and display them shields you from the emotional storms that overwhelm more impressionable people. You’re a steady anchor for those who need support rather than spoken sympathy.\n\nYour strength grows fuller when you start learning to translate the body’s signals into words. Recognizing and naming feelings is a skill, and it trains like any other: an emotion vocabulary, attention to bodily signals. Sometimes difficulty with feelings is the trace of an experience where they were dismissed. In regaining access to your inner language, you don’t lose your clarity — you only add a new dimension to it.',
  },
]

/** Получить позитивный профиль по коду типа */
export function getPositiveProfile(code: PersonalityTypeCode): PositiveProfile | undefined {
  return POSITIVE_PROFILES.find((p) => p.code === code)
}
