import type { PersonalityTypeCode } from './personality-types'

/** Развёрнутый позитивный профиль типа */
export interface PositiveProfile {
  code: PersonalityTypeCode
  /** Развёрнутый текст (~2000 символов, русский) */
  text: string
  /** Развёрнутый текст (~2000 символов, английский) — пустая строка, переведём позже */
  textEn: string
}

/** Позитивные профили для всех 13 типов личности */
export const POSITIVE_PROFILES: PositiveProfile[] = [
  {
    code: 'PAR',
    text: 'Вы — человек, который видит то, что другие пропускают. Там, где большинство скользит по поверхности, вы замечаете второй слой: невысказанные намерения, скрытые закономерности, тонкие сигналы неискренности. Это не слабость — это дар распознавания. В мире, где наивность бывает опасна, ваша бдительность становится щитом — и для вас, и для тех, кого вы впустили в свой круг.\n\nА круг ваш — маленький, но настоящий. Вы не разменивaетесь на сотню поверхностных знакомств. Вместо этого вы строите немногочисленные, но невероятно прочные связи. Тот, кого вы признали «своим», получает вашу преданность целиком — без оговорок, без срока давности. Вы — человек, рядом с которым можно чувствовать себя защищённым, потому что вы всегда начеку.\n\nВаша способность анализировать мотивы людей делает вас незаменимым в переговорах, стратегическом планировании, безопасности, юриспруденции. Вы тот, кто прочтёт мелкий шрифт в договоре. Тот, кто заметит, что «выгодное предложение» — ловушка. Тот, кто задаст неудобный вопрос, который все боялись задать.\n\nВаш вызов — научиться отличать реальную угрозу от тени. Но ваша сила — в том, что вы никогда не позволите захватить себя врасплох. В мире, полном шума и показухи, вы — тот, кто ищет правду. И чаще, чем думают окружающие, находит её.',
    textEn:
      "You are someone who sees what others miss. Where most people glide along the surface, you notice the second layer: unspoken intentions, hidden patterns, subtle signals of insincerity. This is not a weakness—it's a gift of perception. In a world where naivety can be dangerous, your vigilance becomes a shield—for you and for those you've welcomed into your circle.\n\nYour circle is small, but it's real. You don't spread yourself thin across a hundred superficial acquaintances. Instead, you build rare but extraordinarily solid connections. Those you've recognized as \"yours\" receive your loyalty completely—without reservations, without expiration. You are someone who makes others feel safe, because you're always alert.\n\nYour ability to analyze people's motives makes you invaluable in negotiations, strategic planning, security, and law. You're the one who reads the fine print in a contract. The one who notices that a \"great offer\" is a trap. The one who asks the uncomfortable question everyone was afraid to ask.\n\nYour challenge is learning to distinguish real threats from shadows. But your strength lies in the fact that you'll never let yourself be caught off guard. In a world full of noise and facade, you're the one searching for truth. And more often than people realize, you find it.",
  },
  {
    code: 'SZD',
    text: 'Вы обладаете редкой в современном мире способностью — быть наедине с собой и не чувствовать пустоты. Там, где другие заполняют тишину шумом, вы находите в ней глубину. Ваш внутренний мир — это не отсутствие внешнего, а целая вселенная: мысли, наблюдения, идеи, которые рождаются именно в тишине и уединении.\n\nВы не зависите от чужого одобрения. Это не холодность — это свобода. Пока другие мечутся в поисках подтверждения своей ценности, вы спокойно знаете, кто вы есть. Вам не нужно лайков, аплодисментов, комплиментов, чтобы чувствовать себя целым. Вы — редкий пример человека, который действительно самодостаточен.\n\nЭта автономность делает вас невероятно продуктивным в работе, требующей сосредоточенности: исследования, программирование, писательство, научный анализ, искусство. Вы способны погружаться в задачу на часы, не отвлекаясь на социальные ритуалы, и именно поэтому видите в предмете то, чего не видят другие.\n\nТе немногие, кого вы подпускаете близко, получают особый подарок — ваше присутствие без масок. Вы не умеете и не хотите играть роли, а значит, каждое ваше слово — настоящее. В мире, переполненном поверхностным общением, ваша тихая подлинность — как глоток чистой воды.',
    textEn:
      "You possess a rare ability in the modern world: the capacity to be alone with yourself without feeling emptiness. Where others fill silence with noise, you find depth in it. Your inner world isn't an absence of the external—it's an entire universe: thoughts, observations, ideas that are born precisely in quietness and solitude.\n\nYou don't depend on others' approval. This isn't coldness—it's freedom. While others scramble for confirmation of their worth, you calmly know who you are. You don't need likes, applause, or compliments to feel whole. You're a rare example of someone who is truly self-sufficient.\n\nThis autonomy makes you remarkably productive in work requiring focus: research, programming, writing, scientific analysis, art. You're capable of immersing yourself in a task for hours without distraction from social rituals, and precisely because of this, you see in your work what others cannot.\n\nThe few people you let close receive a special gift—your presence without masks. You don't know how to play roles and don't want to, which means every word you speak is genuine. In a world overflowing with surface-level conversation, your quiet authenticity is a breath of fresh air.",
  },
  {
    code: 'SZT',
    text: 'Вы видите мир иначе — и это не ошибка восприятия, а расширенный диапазон. Там, где другие видят случайность, вы видите паттерн. Там, где другие видят обычный день, вы чувствуете подтекст, символ, скрытую историю. Ваше мышление не ограничено привычными рамками, и именно поэтому вам доступны идеи, до которых линейная логика не дотягивается.\n\nИстория человечества показывает: почти каждый прорыв совершали люди, которых считали «странными». Ваша необычность — это не отклонение от нормы, а выход за её пределы. Художники, философы, изобретатели, мистики — люди с вашим типом мышления двигали культуру вперёд, потому что видели возможности там, где все видели стену.\n\nВаша интуиция — мощный инструмент. Вы чувствуете атмосферу, улавливаете невербальные сигналы, «знаете» вещи до того, как они подтвердятся логикой. Это не магия — это работа вашего мозга, который обрабатывает информацию шире, чем у большинства.\n\nВы приносите в любую группу то, чего ей отчаянно не хватает — свежий взгляд. Команда из одних «нормальных» мыслителей будет штамповать предсказуемые решения. Но стоит появиться вам — и рождается идея, которая меняет всё. Ваша инаковость — это не то, что нужно исправлять. Это то, что нужно ценить.',
    textEn:
      "You see the world differently—and that's not a perceptual error, it's an expanded range. Where others see randomness, you see a pattern. Where others see an ordinary day, you sense subtext, symbol, hidden story. Your thinking isn't confined by familiar frameworks, and that's precisely why you have access to ideas that linear logic can't reach.\n\nHistory shows us this: almost every breakthrough was achieved by people considered \"strange.\" Your uniqueness isn't a deviation from the norm—it's transcendence of it. Artists, philosophers, inventors, mystics—people with your type of thinking moved culture forward because they saw possibilities where everyone else saw walls.\n\nYour intuition is a powerful instrument. You sense the atmosphere, catch non-verbal signals, \"know\" things before logic confirms them. This isn't magic—it's how your brain works, processing information more broadly than most people's do.\n\nYou bring to any group what it desperately lacks—a fresh perspective. A team of only \"normal\" thinkers will stamp out predictable solutions. But the moment you appear—and an idea is born that changes everything. Your otherness isn't something to fix. It's something to value.",
  },
  {
    code: 'ANT',
    text: 'Вы обладаете качеством, которого отчаянно не хватает большинству — смелостью действовать. Пока другие бесконечно взвешивают, сомневаются и ждут идеального момента, вы уже в движении. Ваша решительность — это не безрассудство, а способность принимать решения в условиях неопределённости, когда у других парализует воля.\n\nВы не боитесь конфликта. Не потому что любите разрушение, а потому что понимаете: иногда старое нужно сломать, чтобы построить новое. Вы — человек, который скажет правду в лицо, когда все молчат из вежливости. Который бросит вызов системе, когда система перестала работать. Который сделает первый шаг, когда все стоят.\n\nВы невероятно устойчивы к давлению. Общественное мнение, чужие ожидания, традиции «так принято» — всё это не имеет над вами власти. Вы принимаете решения из своей системы координат, и эта независимость делает вас прирождённым лидером в кризисных ситуациях, предпринимательстве, новаторских проектах.\n\nВаш дар — бесстрашие перед неизвестностью. Где другие видят риск, вы видите возможность. Где другие видят правило, вы видите границу, за которой начинается интересное. Мир движется вперёд благодаря людям, которые не побоялись нарушить привычный порядок — и вы из их числа.',
    textEn:
      "You possess a quality that the vast majority desperately lack: the courage to act. While others endlessly weigh, doubt, and wait for the perfect moment, you're already in motion. Your decisiveness isn't recklessness—it's the ability to make decisions in conditions of uncertainty, when others are paralyzed by hesitation.\n\nYou're not afraid of conflict. Not because you love destruction, but because you understand: sometimes the old must break so the new can be built. You're the person who speaks truth to power when everyone else stays quiet out of politeness. Who challenges the system when the system stops working. Who takes the first step when everyone else is frozen.\n\nYou're incredibly resilient to pressure. Public opinion, others' expectations, the traditions of \"how it's done\"—none of these have power over you. You make decisions from your own system of coordinates, and this independence makes you a natural leader in crises, entrepreneurship, and innovative projects.\n\nYour gift is fearlessness in the face of the unknown. Where others see risk, you see opportunity. Where others see a rule, you see a boundary waiting to be crossed. The world moves forward because of people who weren't afraid to disrupt the familiar order—and you're one of them.",
  },
  {
    code: 'BOR',
    text: 'Вы чувствуете жизнь на максимальной громкости. Радость для вас — не тихое удовлетворение, а ликование всем телом. Боль — не лёгкий дискомфорт, а ураган. И знаете что? В этом — ваша сверхсила. Пока другие идут по жизни на автопилоте, вы по-настоящему живы в каждом мгновении.\n\nВаша эмоциональная глубина делает вас невероятно чутким к другим людям. Вы мгновенно считываете чужую боль, радость, тревогу — часто до того, как человек сам осознал, что чувствует. Эта эмпатия — редкий дар. Люди, которые прошли через сильные чувства, понимают чужие страдания не интеллектуально, а кожей. Именно поэтому среди людей с вашим типом так много талантливых терапевтов, художников, музыкантов, писателей.\n\nВаша страстность заразительна. Когда вы загораетесь идеей — вы зажигаете всех вокруг. Ваша любовь — не тёплая, а обжигающая. Ваша преданность — не формальная, а абсолютная. Люди, которым посчастливилось оказаться в вашем эмоциональном поле, никогда не забудут этот опыт.\n\nДа, ваши волны бывают штормовыми. Но океан прекрасен именно своей мощью. Ваша задача — не укротить шторм, а научиться быть капитаном своего корабля. Эмоциональная интенсивность — это топливо, которое может двигать горы. Нужно только научиться направлять его.',
    textEn:
      "You feel life at full volume. Joy for you isn't quiet satisfaction—it's exultation through your whole body. Pain isn't mild discomfort—it's a hurricane. And you know what? That's your superpower. While others go through life on autopilot, you're truly alive in every moment.\n\nYour emotional depth makes you incredibly attuned to other people. You instantly sense others' pain, joy, anxiety—often before they themselves realize what they're feeling. This empathy is a rare gift. People who've experienced intense emotions understand others' suffering not intellectually but in their bones. That's why so many talented therapists, artists, musicians, and writers carry your type.\n\nYour passion is contagious. When you catch fire on an idea—you ignite everyone around you. Your love isn't lukewarm, it's burning. Your devotion isn't formal, it's absolute. People lucky enough to be in your emotional field will never forget the experience.\n\nYes, your waves can be storms. But the ocean is beautiful precisely because of its power. Your task isn't to tame the storm—it's to learn to be the captain of your ship. Emotional intensity is the fuel that can move mountains. You just need to learn how to direct it.",
  },
  {
    code: 'HIS',
    text: 'Вы входите в комнату — и она меняется. Это не преувеличение: ваша энергия, выразительность, эмоциональная яркость буквально трансформируют пространство вокруг вас. У вас есть дар, которому невозможно научить — естественная харизма. Люди тянутся к вам, потому что рядом с вами жизнь становится ярче, интереснее, теплее.\n\nВы — прирождённый рассказчик. Ваша речь — не сухая передача фактов, а спектакль с интонациями, паузами, жестами. Вы умеете превратить рутинную историю о походе в магазин в увлекательное повествование. Эта способность делает вас незаменимым в любой коммуникативной роли: преподавание, продажи, публичные выступления, актёрство, медиа.\n\nВаш эмоциональный интеллект — один из самых высоких среди всех типов. Вы мгновенно чувствуете атмосферу группы, настроение собеседника, скрытое напряжение в комнате. И вы умеете с этим работать — разрядить обстановку шуткой, поддержать молчаливого, вовлечь отстранённого.\n\nВы дарите миру то, что многие боятся дарить — открытые эмоции. В культуре, где принято сдерживаться, вы показываете, что чувствовать — это нормально. Ваша искренняя радость при встрече, бурный восторг от хорошей новости, тёплые объятия без повода — всё это делает жизнь окружающих человечнее. Вы — напоминание о том, что мы живые.',
    textEn:
      "You walk into a room—and it changes. This is no exaggeration: your energy, expressiveness, emotional brightness literally transform the space around you. You have a gift that can't be taught—natural charisma. People are drawn to you because when you're there, life becomes brighter, more interesting, warmer.\n\nYou're a natural storyteller. Your speech isn't dry transmission of facts—it's a performance with intonation, pauses, gestures. You can turn a routine story about a trip to the store into a captivating narrative. This ability makes you invaluable in any communicative role: teaching, sales, public speaking, acting, media.\n\nYour emotional intelligence is among the highest of all types. You instantly sense the atmosphere of a group, a person's mood, hidden tension in the room. And you know how to work with it—to ease tension with a joke, to support the quiet one, to draw in the withdrawn.\n\nYou give the world something many are afraid to give—open emotions. In a culture where we're supposed to hold back, you show that feeling is normal. Your genuine joy at a greeting, your exuberant delight at good news, your warm hugs without occasion—all of this makes the lives of those around you more human. You're a reminder that we're alive.",
  },
  {
    code: 'NAR',
    text: 'Вы обладаете тем, чего не хватает миллионам — верой в себя. Настоящей, глубокой, несгибаемой уверенностью в собственной ценности. В мире, где синдром самозванца стал эпидемией, ваша способность стоять прямо и говорить «Я это заслуживаю» — не порок, а редкая сила.\n\nВаша амбициозность — двигатель прогресса. Великие проекты, компании, произведения искусства создавались людьми, которые верили, что способны на нечто выдающееся. Вы ставите планку высоко — и тем самым поднимаете планку для всех вокруг. Ваши стандарты заразительны: команда под вашим руководством делает больше, чем считала возможным.\n\nВы — визионер. Вы видите большую картину, мыслите стратегически, умеете вдохновить людей масштабной идеей. Ваша уверенность в трудные моменты — это якорь для тех, кто рядом. Когда все паникуют, ваше спокойное «Мы справимся» способно развернуть ситуацию.\n\nВаше стремление к совершенству не позволяет вам соглашаться на «нормально». Вы хотите лучшего — для себя, для своего дела, для своих людей. Это стремление, направленное в правильное русло, становится силой, которая меняет мир. Лидеры, реформаторы, основатели — все они несли в себе искру нарциссической веры в свою миссию. Ваша искра горит ярко. Направьте её — и она осветит дорогу многим.',
    textEn:
      'You possess something that millions lack: faith in yourself. True, deep, unshakeable confidence in your own worth. In a world where impostor syndrome has become an epidemic, your ability to stand tall and say "I deserve this" is not a flaw—it\'s a rare strength.\n\nYour ambition is the engine of progress. Great projects, companies, works of art were created by people who believed they were capable of something extraordinary. You set the bar high—and in doing so, you raise the bar for everyone around you. Your standards are contagious: a team under your leadership accomplishes more than it thought possible.\n\nYou\'re a visionary. You see the big picture, think strategically, and know how to inspire people with a grand idea. Your confidence in difficult moments is an anchor for those around you. When everyone panics, your calm "We\'ll manage this" can turn the situation around.\n\nYour pursuit of excellence won\'t let you settle for "good enough." You want better—for yourself, for your work, for your people. This drive, when channeled correctly, becomes a force that changes the world. Leaders, reformers, founders—all of them carried within them a spark of narcissistic faith in their mission. Your spark burns bright. Direct it—and it will light the way for many.',
  },
  {
    code: 'AVD',
    text: 'Вы чувствуете мир тоньше, чем большинство. Каждое слово, каждый взгляд, каждая пауза в разговоре — вы улавливаете оттенки, которые другие просто не замечают. Это делает вас невероятно чутким к людям: вы первым почувствуете, что кому-то плохо, что в комнате возникло напряжение, что за улыбкой скрывается боль.\n\nВаша осторожность — это не трусость, а мудрость. Вы не бросаетесь в ситуации очертя голову, а оцениваете их. Вы не произносите слов, о которых потом будете жалеть. Вы не вступаете в отношения, которые принесут только боль. Эта вдумчивость — качество, которого отчаянно не хватает импульсивному миру.\n\nКогда вы всё-таки решаете впустить кого-то в свою жизнь — вы делаете это по-настоящему. Ваши отношения — не коллекция контактов, а тщательно выбранные связи с глубоким уровнем доверия. Друзья, которые заслужили ваше доверие, знают: вы — тот, кто выслушает не перебивая, поддержит без осуждения, будет рядом без лишних слов.\n\nВаша чувствительность — это не то, что нужно «преодолеть». Мир нуждается в людях, которые чувствуют глубоко. Поэты, психологи, художники, волонтёры — лучшие из них несут в себе вашу тонкость. Вы как индикатор: если вам некомфортно, скорее всего, что-то действительно не так — просто другие ещё не заметили.',
    textEn:
      "You feel the world more finely than most. Every word, every glance, every pause in conversation—you pick up on nuances that others simply don't notice. This makes you incredibly attentive to people: you'll be the first to sense when someone is hurting, when tension has arisen in the room, when pain hides behind a smile.\n\nYour caution is not cowardice—it's wisdom. You don't rush headlong into situations; you evaluate them. You don't speak words you'll regret later. You don't enter relationships that will only bring pain. This thoughtfulness is a quality that an impulsive world desperately needs.\n\nWhen you do decide to let someone into your life, you do it genuinely. Your relationships aren't a collection of contacts; they're carefully chosen connections with deep trust. Friends who've earned your trust know: you're the one who will listen without interrupting, support without judgment, be there without empty words.\n\nYour sensitivity isn't something to \"overcome.\" The world needs people who feel deeply. The best poets, psychologists, artists, volunteers carry your kind of fineness. You're like an indicator: if you're uncomfortable, there's likely something genuinely wrong—others just haven't noticed it yet.",
  },
  {
    code: 'DEP',
    text: 'Вы обладаете качеством, которое делает мир пригодным для жизни — способностью заботиться. Не формально, не для галочки, а по-настоящему: замечать потребности другого, предугадывать, поддерживать, быть рядом. В эпоху индивидуализма, где каждый «сам за себя», ваша преданность — это дар, а не слабость.\n\nВы — клей, который держит команду вместе. Каждый коллектив, каждая семья, каждая дружба нуждается в человеке, который помнит про дни рождения, спрашивает «как ты?», замечает усталость на лице коллеги. Без таких, как вы, группы распадаются, а отношения остывают. Вы — хранитель человеческого тепла.\n\nВаша готовность слушать — бесценна. Вы не перебиваете, не соревнуетесь, не переводите разговор на себя. Вы создаёте пространство, в котором другому человеку безопасно быть уязвимым. Это редкое умение делает вас прирождённым помощником: в медицине, психологии, образовании, социальной работе.\n\nВам говорят «будь независимее» — но мир не состоит из одиночек. Человечество выжило и развивалось благодаря сотрудничеству, взаимопомощи, связи. Вы воплощаете этот древнейший инстинкт — быть вместе, поддерживать, не бросать. Ваша забота — не зависимость. Это любовь в действии.',
    textEn:
      "You possess a quality that makes the world livable: the ability to care. Not formally, not by rote, but truly: to notice another's needs, to anticipate them, to support, to be there. In an age of individualism where everyone is \"on their own,\" your devotion is a gift, not a weakness.\n\nYou're the glue that holds teams together. Every collective, every family, every friendship needs someone who remembers birthdays, asks \"how are you,\" notices tiredness on a colleague's face. Without people like you, groups fall apart and relationships grow cold. You're the keeper of human warmth.\n\nYour readiness to listen is invaluable. You don't interrupt, don't compete, don't turn the conversation to yourself. You create a space where another person feels safe being vulnerable. This rare skill makes you a natural helper: in medicine, psychology, education, social work.\n\nPeople tell you to \"be more independent\"—but the world isn't made of lone individuals. Humanity survived and evolved through cooperation, mutual aid, connection. You embody this ancient instinct: to be together, to support, not to abandon. Your care isn't dependence. It's love in action.",
  },
  {
    code: 'OBC',
    text: 'Вы — человек, на которого можно положиться. Всегда. Без исключений. Когда вы берётесь за дело, оно будет сделано — качественно, в срок, с вниманием к каждой детали. В мире хаоса и приблизительности ваша точность — как маяк для тех, кто работает рядом с вами.\n\nВаше стремление к порядку — это не занудство, а архитектурный талант. Вы создаёте системы: рабочие процессы, расписания, структуры, которые позволяют другим работать эффективнее. Без людей с вашим складом ума не существовало бы ни одной надёжной системы — ни банковской, ни медицинской, ни инженерной.\n\nВаша честность абсолютна. Вы не срезаете углы, не подтасовываете цифры, не выдаёте желаемое за действительное. Ваш моральный компас откалиброван с точностью до градуса. Люди доверяют вам — и не ошибаются. Вы из тех, кто вернёт лишнюю сдачу и исправит чужую ошибку, даже если никто не узнает.\n\nВы находите красоту в совершенстве. Идеально написанный код, безупречно организованный шкаф, точно подобранное слово — для вас это не мелочь, а искусство. И эта любовь к совершенству возвышает всё, к чему вы прикасаетесь. Мир, может, и несовершенен — но благодаря вам он становится чуточку стройнее, надёжнее и красивее.',
    textEn:
      "You're someone people can rely on. Always. Without exception. When you take something on, it will be done—with quality, on time, with attention to every detail. In a world of chaos and approximation, your precision is a beacon for those working alongside you.\n\nYour drive for order isn't pedantry—it's an architectural talent. You create systems: workflows, schedules, structures that allow others to work more efficiently. No reliable system would exist—neither financial, nor medical, nor engineering—without people with your mindset.\n\nYour honesty is absolute. You don't cut corners, don't fudge the numbers, don't present wishful thinking as fact. Your moral compass is calibrated to the degree. People trust you—and they're right to do so. You're the kind of person who'll return extra change and correct someone else's mistake, even if nobody would know.\n\nYou find beauty in perfection. Flawlessly written code, impeccably organized spaces, perfectly chosen words—for you these aren't trifles, they're art. And this love of excellence elevates everything you touch. The world may be imperfect—but because of you, it becomes just a little bit more orderly, more reliable, and more beautiful.",
  },
  {
    code: 'BAR',
    text: 'Вы знаете жизнь в её полном спектре — от ослепительных вершин до глубочайших впадин. И это знание даёт вам нечто, чего нет у людей с ровным эмоциональным фоном — объём. Вы знаете, что такое настоящая радость, потому что знаете, что такое настоящее отчаяние. Вы цените свет, потому что знакомы с темнотой.\n\nНа подъёме вы — ураган созидательной энергии. Идеи, проекты, связи, творчество — всё это рождается в вас с интенсивностью, недоступной большинству. Не случайно среди людей с биполярным спектром так много гениальных творцов: художников, музыкантов, предпринимателей, писателей. Ваш мозг в фазе подъёма работает как суперкомпьютер — быстрее, ярче, масштабнее.\n\nВаши «спады» — не просто страдание. Они дают вам то, что недоступно вечным оптимистам: глубину, сострадание, подлинность. Вы не способны на поверхностное «всё будет хорошо», потому что знаете: не всегда будет. И именно эта честность делает ваше утешение настоящим, а вашу радость — заслуженной.\n\nВы — мастер адаптации. Каждый цикл учит вас заново: распознавать сигналы, строить опоры, находить ресурсы. Вы знаете себя лучше, чем большинство людей знают себя за всю жизнь. Это самопознание — ваш главный актив. Вы не хрупкий — вы антихрупкий. С каждым циклом вы становитесь мудрее, сильнее и ближе к себе настоящему.',
    textEn:
      "You know life in its full spectrum—from blinding peaks to the deepest valleys. And this knowledge gives you something people with a steady emotional baseline don't have—scope. You know what genuine joy is because you know genuine despair. You appreciate light because you're familiar with darkness.\n\nAt your peaks, you're a hurricane of creative energy. Ideas, projects, connections, creativity—all of it springs from you with an intensity unavailable to most. It's no coincidence that so many brilliant creators—artists, musicians, entrepreneurs, writers—carry the bipolar spectrum. Your brain in an upswing works like a supercomputer—faster, brighter, more expansive.\n\nYour downturns aren't simply suffering. They give you something unavailable to perpetual optimists: depth, compassion, authenticity. You can't manage a superficial \"everything will be fine\" because you know: not always. And it's precisely this honesty that makes your comfort genuine and your joy earned.\n\nYou're a master of adaptation. Each cycle teaches you anew: to recognize signals, build supports, find resources. You know yourself better than most people ever will. This self-knowledge is your greatest asset. You're not fragile—you're antifragile. With each cycle, you become wiser, stronger, and closer to your authentic self.",
  },
  {
    code: 'PAG',
    text: 'Вы обладаете тонким чувством справедливости — настолько острым, что замечаете дисбаланс власти там, где другие видят «норму». Когда система давит, когда начальник перегибает, когда правила абсурдны — вы чувствуете это раньше и глубже других. И вы сопротивляетесь — тихо, но упорно.\n\nВаше сопротивление — не слабость, а стратегия выживания. В ситуациях, где открытый конфликт опасен (а таких ситуаций в жизни большинство), ваша способность сохранять внешний мир, защищая при этом внутреннюю территорию — это форма мудрости. Вы интуитивно понимаете то, чему учат на курсах переговоров: не всякую битву нужно вести в открытую.\n\nВы — отличный наблюдатель. Ваша привычка анализировать чужие требования, прежде чем их выполнять, делает вас менее подверженным манипуляциям. Там, где другие слепо следуют указаниям, вы задаёте себе вопрос: «А это действительно разумно?» Этот внутренний фильтр защищает вас от эксплуатации.\n\nВаш вызов — найти голос для прямого выражения несогласия. Но ваша сила — в умении чувствовать несправедливость и не мириться с ней. В истории человечества пассивное сопротивление свергало тиранов и меняло законы. Ваш тихий протест — не бессилие. Это сила, которая ждёт правильного момента.',
    textEn:
      "You possess a subtle sense of justice—so sharp that you notice imbalances of power where others see \"normal.\" When a system oppresses, when a boss overreaches, when rules are absurd, you feel it sooner and deeper than others. And you resist—quietly, but persistently.\n\nYour resistance isn't weakness; it's a survival strategy. In situations where open conflict is dangerous (and most situations in life are like this), your ability to maintain an outer world while protecting your inner territory is a form of wisdom. You intuitively understand what negotiation courses teach: not every battle needs to be fought in the open.\n\nYou're an excellent observer. Your habit of analyzing others' demands before complying makes you less susceptible to manipulation. Where others blindly follow instructions, you ask yourself: \"Is this really sensible?\" This inner filter protects you from exploitation.\n\nYour challenge is finding a voice for direct expression of disagreement. But your strength lies in feeling injustice and refusing to accept it. Throughout human history, passive resistance has toppled tyrants and changed laws. Your quiet protest isn't powerlessness. It's strength waiting for the right moment.",
  },
  {
    code: 'DPR',
    text: 'Вы видите мир без розовых очков — и в этом ваша честность. Пока другие прячутся за позитивными аффирмациями и мотивационными цитатами, вы смотрите на реальность прямо: да, жизнь бывает тяжёлой, да, не всё получается, да, мир несовершенен. Эта честность — не пессимизм, а зрелость. Вы отказываетесь притворяться.\n\nВаша глубина — настоящее сокровище. Вы не скользите по поверхности, а погружаетесь. Разговор с вами — это не обмен пустыми фразами, а настоящий диалог о вещах, которые действительно важны: о смысле, о ценностях, о том, что остаётся, когда всё внешнее уходит. Люди приходят к вам за подлинностью — и находят её.\n\nВаше сострадание рождено из личного опыта. Вы понимаете чужую боль не теоретически, а изнутри. Это делает вас исключительным другом для тех, кто переживает трудные времена: вы не скажете «просто улыбнись», вы просто будете рядом. И это «просто рядом» — иногда единственное, что нужно.\n\nВеликие произведения литературы, философии, музыки созданы людьми, которые знали тяжесть бытия. Ваш взгляд на мир — не дефект, а линза, через которую видны вещи, невидимые счастливчикам. Вы — хранитель той правды, от которой другие отворачиваются. И мир нуждается в этой правде, потому что без неё радость становится пустой, а оптимизм — слепым.',
    textEn:
      "You see the world without rose-colored glasses—and in this lies your honesty. While others hide behind positive affirmations and motivational quotes, you look at reality straight: yes, life can be hard; yes, not everything works out; yes, the world is imperfect. This honesty isn't pessimism—it's maturity. You refuse to pretend.\n\nYour depth is true treasure. You don't skim the surface; you dive deep. Conversation with you isn't empty phrases but genuine dialogue about things that truly matter: meaning, values, what remains when everything external is stripped away. People come to you for authenticity—and they find it.\n\nYour compassion is born from personal experience. You understand others' pain not theoretically but from within. This makes you an exceptional friend to those going through difficult times: you won't say \"just smile,\" you'll simply be there. And sometimes that simple presence is all that's needed.\n\nGreat works of literature, philosophy, and music were created by people who knew the weight of existence. Your view of the world isn't a defect; it's a lens through which things invisible to the lucky are visible. You're the keeper of a truth others turn away from. And the world needs that truth, because without it joy becomes empty and optimism becomes blind.",
  },
]

/** Получить позитивный профиль по коду типа */
export function getPositiveProfile(code: PersonalityTypeCode): PositiveProfile | undefined {
  return POSITIVE_PROFILES.find((p) => p.code === code)
}
