'use client'

import { createProduct } from '@/app/_actions/product.action'
import { ProductCreateFormSchema } from '@/generated/form-schemas'
import { Heading, Stack, Text } from '@chakra-ui/react'
import { Form } from '@letar/forms'

export default function NewProductPage() {
  return (
    <Stack gap={6}>
      <div>
        <Heading size="lg">Create Product</Heading>
        <Text color="fg.muted">
          This form uses a schema generated by @letar/zenstack-form-plugin from schema.zmodel. Data is saved to
          PostgreSQL via Server Action.
        </Text>
      </div>

      <Form.FromSchema
        schema={ProductCreateFormSchema}
        initialValue={{
          name: '',
          description: '',
          price: 0,
          status: 'DRAFT' as const,
          tags: [] as string[],
          rating: 0,
        }}
        onSubmit={async (data) => {
          await createProduct(data as Parameters<typeof createProduct>[0])
        }}
        submitLabel="Create Product"
        debug
      />
    </Stack>
  )
}
