FROM letar-node-runtime:24 AS runner
WORKDIR /app

# Копируем standalone build
COPY --chown=nextjs:nodejs apps/archetest/.next/standalone ./
COPY --chown=nextjs:nodejs apps/archetest/.next/static ./apps/archetest/.next/static
COPY --chown=nextjs:nodejs apps/archetest/public ./apps/archetest/public

USER nextjs

EXPOSE 3012

ENV PORT=3012
ENV HOSTNAME="0.0.0.0"

CMD ["node", "apps/archetest/server.js"]
