export {
  calculateCancelDeadline,
  cancelPenalty,
  chargePenalty,
  getPenaltySettings,
  isLateCancellation,
  markPenaltyAsPaid,
  type CancelPenaltyResult,
  type ChargePenaltyResult,
  type GetSettingsResult,
  type InstructorSettings,
  type MarkPaidResult,
  type PenaltyData,
  type PenaltyRepository,
} from './penalty-service'
