// AUTO-GENERATED by @letar/zenstack-form-plugin
// DO NOT EDIT MANUALLY

/**
 * All form translation keys.
 *
 * Pattern:
 * - {ModelName}.{fieldName}.{title|placeholder|description}
 * - {EnumName}.{VALUE}.{label}
 * - validation.{code} — Zod validation errors
 * - validation.{code}.{origin} — errors with type (string, number, array, date)
 */
export type FormI18nKey =
  | 'CrossPostStatus.FAILED.label'
  | 'CrossPostStatus.PENDING.label'
  | 'CrossPostStatus.PUBLISHED.label'
  | 'ImageCategory.AVATAR.label'
  | 'ImageCategory.BLOG.label'
  | 'ImageCategory.CONTENT.label'
  | 'ImageCategory.OTHER.label'
  | 'LearningItemType.ARTICLE.label'
  | 'LearningItemType.BOOK.label'
  | 'LearningItemType.CONFERENCE.label'
  | 'LearningItemType.COURSE.label'
  | 'LearningItemType.OTHER.label'
  | 'LearningItemType.PODCAST.label'
  | 'LearningItemType.VIDEO.label'
  | 'LearningStatus.ABANDONED.label'
  | 'LearningStatus.COMPLETED.label'
  | 'LearningStatus.IN_PROGRESS.label'
  | 'LearningStatus.WANT_TO_LEARN.label'
  | 'SkillLevel.ADVANCED.label'
  | 'SkillLevel.BEGINNER.label'
  | 'SkillLevel.EXPERT.label'
  | 'SkillLevel.INTERMEDIATE.label'
  | 'SocialPlatformType.BLUESKY.label'
  | 'SocialPlatformType.FACEBOOK.label'
  | 'SocialPlatformType.INSTAGRAM.label'
  | 'SocialPlatformType.LINKEDIN.label'
  | 'SocialPlatformType.MASTODON.label'
  | 'SocialPlatformType.TELEGRAM.label'
  | 'SocialPlatformType.TWITTER.label'
  | 'SocialPlatformType.VK.label'
  | 'SurveyQuestionType.MULTI_CHOICE.label'
  | 'SurveyQuestionType.RATING.label'
  | 'SurveyQuestionType.SCALE.label'
  | 'SurveyQuestionType.SINGLE_CHOICE.label'
  | 'SurveyQuestionType.TEXT.label'
  | 'UserRole.ADMIN.label'
  | 'UserRole.USER.label'
  | 'validation.custom'
  | 'validation.invalid_element'
  | 'validation.invalid_format.base64'
  | 'validation.invalid_format.cuid'
  | 'validation.invalid_format.date'
  | 'validation.invalid_format.datetime'
  | 'validation.invalid_format.email'
  | 'validation.invalid_format.emoji'
  | 'validation.invalid_format.ip'
  | 'validation.invalid_format.json_string'
  | 'validation.invalid_format.jwt'
  | 'validation.invalid_format.lowercase'
  | 'validation.invalid_format.regex'
  | 'validation.invalid_format.time'
  | 'validation.invalid_format.uppercase'
  | 'validation.invalid_format.url'
  | 'validation.invalid_format.uuid'
  | 'validation.invalid_key'
  | 'validation.invalid_type'
  | 'validation.invalid_union'
  | 'validation.invalid_value'
  | 'validation.not_multiple_of'
  | 'validation.required'
  | 'validation.too_big.array'
  | 'validation.too_big.date'
  | 'validation.too_big.file'
  | 'validation.too_big.number'
  | 'validation.too_big.set'
  | 'validation.too_big.string'
  | 'validation.too_small.array'
  | 'validation.too_small.date'
  | 'validation.too_small.file'
  | 'validation.too_small.number'
  | 'validation.too_small.set'
  | 'validation.too_small.string'
  | 'validation.unrecognized_keys'

/**
 * Total key count: 73
 */
export const FORM_I18N_KEY_COUNT = 73
