-- CreateEnum
CREATE TYPE "TrackPreference" AS ENUM ('RUSSIAN_DUB', 'ORIGINAL_SUB', 'AUTO');

-- CreateEnum
CREATE TYPE "RelationKind" AS ENUM ('SEQUEL', 'PREQUEL', 'SIDE_STORY', 'PARENT_STORY', 'SUMMARY', 'FULL_STORY', 'SPIN_OFF', 'ADAPTATION', 'CHARACTER', 'ALTERNATIVE_VERSION', 'ALTERNATIVE_SETTING', 'OTHER');
