import type { Enum } from '@zenstackhq/language/ast'
import { describe, expect, it } from 'vitest'
import { extractEnumInfo, generateEnumCode } from './enum-generator.js'
import type { EnumInfo, I18nConfig } from './types.js'

/**
 * Минимальная фикстура Enum-узла AST ZenStack.
 * Реальный Langium AstNode несёт служебные поля ($container, $cstNode, $document
 * и т.д.), но extractEnumInfo читает только name/fields/comments — этого достаточно.
 */
function makeEnumFixture(): Enum {
  return {
    $type: 'Enum',
    name: 'RecipeType',
    comments: [],
    attributes: [],
    fields: [
      { $type: 'EnumField', name: 'SWEET', comments: ['/// Сладкий'], attributes: [] },
      { $type: 'EnumField', name: 'SALTY_SNACK', comments: [], attributes: [] },
    ],
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  } as any
}

describe('extractEnumInfo', () => {
  it('извлекает имя enum и значения с label из doc-комментария', () => {
    const info = extractEnumInfo(makeEnumFixture())

    expect(info.name).toBe('RecipeType')
    expect(info.values).toEqual([
      { name: 'SWEET', label: 'Сладкий' },
      { name: 'SALTY_SNACK', label: 'Salty Snack' },
    ])
  })

  it('без комментария падает обратно на toTitleCase(name)', () => {
    const info = extractEnumInfo(makeEnumFixture())
    const salty = info.values.find((v) => v.name === 'SALTY_SNACK')
    expect(salty?.label).toBe('Salty Snack')
  })
})

describe('generateEnumCode', () => {
  const enumInfo: EnumInfo = {
    name: 'RecipeType',
    values: [
      { name: 'SWEET', label: 'Сладкий' },
      { name: 'SALTY', label: 'Солёный' },
    ],
  }

  it('генерирует Zod-схему со списком значений enum', () => {
    const code = generateEnumCode(enumInfo)
    expect(code).toContain(`export const RecipeTypeFormSchema = z.enum(['SWEET', 'SALTY'])`)
  })

  it('генерирует options с value/label без i18nKey, когда i18n выключен', () => {
    const code = generateEnumCode(enumInfo, null)
    expect(code).toContain(`value: 'SWEET', label: 'Сладкий'`)
    expect(code).not.toContain('i18nKey')
  })

  it('добавляет i18nKey в options, когда i18n включён', () => {
    const i18nConfig: I18nConfig = {
      enabled: true,
      output: './messages/form-schemas',
      defaultLocale: 'en',
      locales: ['en', 'ru'],
    }
    const code = generateEnumCode(enumInfo, i18nConfig)
    expect(code).toContain(`i18nKey: 'RecipeType.SWEET'`)
    expect(code).toContain(`i18nKey: 'RecipeType.SALTY'`)
  })

  it('генерирует объект Labels для всех значений', () => {
    const code = generateEnumCode(enumInfo)
    expect(code).toContain('export const RecipeTypeLabels = {')
    expect(code).toContain(`SWEET: 'Сладкий'`)
    expect(code).toContain(`SALTY: 'Солёный'`)
  })

  it('генерирует тип значения через z.infer', () => {
    const code = generateEnumCode(enumInfo)
    expect(code).toContain('export type RecipeTypeValue = z.infer<typeof RecipeTypeFormSchema>')
  })

  it('помечает файл как AUTO-GENERATED', () => {
    const code = generateEnumCode(enumInfo)
    expect(code).toContain('AUTO-GENERATED by @letar/zenstack-form-plugin')
    expect(code).toContain('DO NOT EDIT MANUALLY')
  })
})
