import { describe, expect, it } from 'vitest'
import {
  assertValidFieldType,
  collectRegistryKeys,
  findRegistryWarnings,
  generateRegistryKeysCode,
  parseFieldRegistryType,
} from './registry-keys.js'
import type { FormFieldMeta, ModelInfo } from './types.js'

/** Модель с полями `имя → formMeta` — остальное для разбора ключей не важно */
function model(name: string, fields: Record<string, FormFieldMeta>, type = 'String'): ModelInfo {
  return {
    name,
    excludedFields: [],
    fields: Object.entries(fields).map(([fieldName, formMeta]) => ({
      name: fieldName,
      type,
      isRequired: true,
      isList: false,
      isEnum: false,
      formMeta,
    })),
  }
}

describe('P1: parseFieldRegistryType — грамматика ключа реестра', () => {
  it.each([
    ['Select.WorkCategory', 'Select', 'WorkCategory'],
    ['Combobox.Counterparty', 'Combobox', 'Counterparty'],
    ['Listbox.Tag2', 'Listbox', 'Tag2'],
  ])('«%s» — ключ реестра', (value, namespace, key) => {
    expect(parseFieldRegistryType(value)).toEqual({ namespace, key })
  })

  it.each(['select', 'tags', 'currency', 'combobox', 'string'])('встроенный тип «%s» без точки — не ключ', (value) => {
    expect(parseFieldRegistryType(value)).toBeNull()
  })

  it.each(['Foo.X', 'Select.lower', 'Select.', 'Select', 'Select.Work.Cat', 'select.Work', 'Select.Work-Cat', '.Work'])(
    'неверный синтаксис «%s» — null',
    (value) => {
      expect(parseFieldRegistryType(value)).toBeNull()
    },
  )
})

describe('P1: assertValidFieldType — ошибка generate', () => {
  it.each(['select', 'tags', 'Select.WorkCategory', 'Combobox.A'])('«%s» допустим', (value) => {
    expect(() => assertValidFieldType('Work', 'categoryId', value)).not.toThrow()
  })

  it('неизвестное пространство — ошибка с Модель.поле и причиной', () => {
    expect(() => assertValidFieldType('Work', 'categoryId', 'Foo.X')).toThrow(
      /Work\.categoryId.*Foo\.X.*пространство «Foo»/,
    )
  })

  it.each(['Select.lower', 'Select.', 'Select.Work.Cat'])('«%s» — ошибка про имя ключа', (value) => {
    expect(() => assertValidFieldType('Work', 'categoryId', value)).toThrow(/Work\.categoryId.*имя ключа/)
  })
})

describe('P2: collectRegistryKeys', () => {
  it('пустая схема — пустые пространства', () => {
    expect(collectRegistryKeys([model('Work', { title: { title: 'Название' } })])).toEqual({
      keys: { Select: [], Combobox: [], Listbox: [] },
      usages: {},
    })
  })

  it('собирает ключи по нескольким моделям, дедуплицирует и сортирует', () => {
    const data = collectRegistryKeys([
      model('Work', {
        categoryId: { fieldType: 'Select.WorkCategory' },
        counterpartyId: { fieldType: 'Combobox.Counterparty' },
        status: { fieldType: 'select' },
      }),
      model('Estimate', {
        categoryId: { fieldType: 'Select.WorkCategory' },
        unitId: { fieldType: 'Select.Unit' },
        tagIds: { fieldType: 'Listbox.Tag' },
      }),
    ])

    expect(data.keys).toEqual({
      Select: ['Unit', 'WorkCategory'],
      Combobox: ['Counterparty'],
      Listbox: ['Tag'],
    })
    expect(data.usages).toEqual({
      'Select.Unit': ['Estimate.unitId'],
      'Select.WorkCategory': ['Work.categoryId', 'Estimate.categoryId'],
      'Combobox.Counterparty': ['Work.counterpartyId'],
      'Listbox.Tag': ['Estimate.tagIds'],
    })
  })
})

describe('P2: generateRegistryKeysCode', () => {
  it('пустые пространства — [] и пустой formRegistryUsages, шапка и русские комментарии, без импортов', () => {
    const code = generateRegistryKeysCode(collectRegistryKeys([]))

    expect(code.startsWith('// AUTO-GENERATED by @letar/zenstack-form-plugin\n// DO NOT EDIT MANUALLY\n')).toBe(true)
    expect(code).not.toMatch(/^import /m)
    expect(code).toContain('Select: [],')
    expect(code).toContain('Combobox: [],')
    expect(code).toContain('Listbox: [],')
    expect(code).toContain('} as const')
    expect(code).toContain('export type FormSelectKey = (typeof formRegistryKeys.Select)[number]')
    expect(code).toContain('export type FormComboboxKey = (typeof formRegistryKeys.Combobox)[number]')
    expect(code).toContain('export type FormListboxKey = (typeof formRegistryKeys.Listbox)[number]')
    expect(code).toContain('export const formRegistryUsages = {} as const')
    expect(code).toContain('/** Ключи реестра createForm')
  })

  it('ключи и места использования по образцу §17.4', () => {
    const code = generateRegistryKeysCode(
      collectRegistryKeys([
        model('Work', {
          categoryId: { fieldType: 'Select.WorkCategory' },
          counterpartyId: { fieldType: 'Combobox.Counterparty' },
        }),
        model('Estimate', { categoryId: { fieldType: 'Select.WorkCategory' } }),
      ]),
    )

    expect(code).toContain(`Select: ['WorkCategory'],`)
    expect(code).toContain(`Combobox: ['Counterparty'],`)
    expect(code).toContain(`Listbox: [],`)
    expect(code).toContain(`'Select.WorkCategory': ['Work.categoryId', 'Estimate.categoryId'],`)
    expect(code).toContain(`'Combobox.Counterparty': ['Work.counterpartyId'],`)
  })
})

describe('findRegistryWarnings — проверка form.relation.* по моделям схемы', () => {
  const schema = new Map<string, ReadonlySet<string>>([
    ['User', new Set(['id', 'name', 'note'])],
    ['Order', new Set(['id', 'authorId', 'author'])],
  ])

  it('корректная связь — без предупреждений', () => {
    const models = [
      model('Order', { authorId: { relation: { model: 'User', labelField: 'name', descriptionField: 'note' } } }),
    ]
    expect(findRegistryWarnings(models, schema)).toEqual([])
  })

  it('нет такой модели — предупреждение', () => {
    const models = [model('Order', { authorId: { relation: { model: 'Ghost', labelField: 'name' } } })]
    const warnings = findRegistryWarnings(models, schema)
    expect(warnings).toHaveLength(1)
    expect(warnings[0]).toMatch(/Order\.authorId.*form\.relation\.model.*«Ghost»/)
  })

  it('labelField и descriptionField — не поля модели', () => {
    const models = [
      model('Order', { authorId: { relation: { model: 'User', labelField: 'title', descriptionField: 'about' } } }),
    ]
    const warnings = findRegistryWarnings(models, schema)
    expect(warnings).toHaveLength(2)
    expect(warnings[0]).toMatch(/Order\.authorId.*labelField.*«User».*«title»/)
    expect(warnings[1]).toMatch(/Order\.authorId.*descriptionField.*«User».*«about»/)
  })

  it('без relation.model берётся тип поля (поле-ссылка на модель)', () => {
    const models = [model('Order', { author: { relation: { labelField: 'title' } } }, 'User')]
    const warnings = findRegistryWarnings(models, schema)
    expect(warnings).toHaveLength(1)
    expect(warnings[0]).toMatch(/Order\.author.*labelField.*«User».*«title»/)
  })

  it('без relation.model и без ссылки на модель — поля не проверяем', () => {
    const models = [model('Order', { authorId: { relation: { labelField: 'title' } } })]
    expect(findRegistryWarnings(models, schema)).toEqual([])
  })

  it('ключ реестра и form.relation.* на одном поле — побеждает ключ', () => {
    const models = [
      model('Order', {
        authorId: { fieldType: 'Select.Author', relation: { model: 'User', labelField: 'name' } },
      }),
    ]
    const warnings = findRegistryWarnings(models, schema)
    expect(warnings).toHaveLength(1)
    expect(warnings[0]).toMatch(/Order\.authorId.*Select\.Author.*побеждает ключ.*relation.*игнорируется/)
  })
})
