FROM letar-node-runtime:24 AS runner
WORKDIR /app

# Копируем standalone build
COPY --chown=nextjs:nodejs apps/auth-hub/.next/standalone ./
COPY --chown=nextjs:nodejs apps/auth-hub/.next/static ./apps/auth-hub/.next/static
COPY --chown=nextjs:nodejs apps/auth-hub/public ./apps/auth-hub/public

USER nextjs

EXPOSE 3010

ENV PORT=3010
ENV HOSTNAME="0.0.0.0"

CMD ["node", "apps/auth-hub/server.js"]
