FROM node:24-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Копируем standalone build
COPY --chown=nextjs:nodejs apps/auth-hub/.next/standalone ./
COPY --chown=nextjs:nodejs apps/auth-hub/.next/static ./apps/auth-hub/.next/static
COPY --chown=nextjs:nodejs apps/auth-hub/public ./apps/auth-hub/public

USER nextjs

EXPOSE 3010

ENV PORT=3010
ENV HOSTNAME="0.0.0.0"

CMD ["node", "apps/auth-hub/server.js"]
